lab_1/urls.py
from django.urls import re_path
from .views import *
#url for app
app_name = "lab_1"
urlpatterns = [
    re_path(r'^$', index, name='index'),
    re_path(r'^home$', home, name='home'),
    re_path(r'^about$', about, name='about'),
    re_path(r'^critics$', critics, name='critics'),
    re_path(r'^form$', form, name='form'),
    re_path(r'^schedule$', schedule, name='schedule'),
]	

lab_2/urls.py
from django.urls import path
from .views import index

#url for app, add your URL Configuration

urlpatterns = [
#TODO Implement this
]

lab_8/urls.py
from django.urls import re_path
from .views import *
#url for app
app_name = "lab_8"
urlpatterns = [
    re_path(r'^$', index, name='index'),
]	

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin
from lab_1.views import index as index_lab1


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^lab-1/', include('lab_1.urls')),
    re_path(r'^lab-2/', include('lab_2.urls')),
    re_path(r'^$', index_lab1, name='index'),
    re_path(r'^lab-8/', include('lab_8.urls')),
]

lab_1/models.py
from django.db import models

# Create your models here.
class Schedule (models.Model):
        date = models.DateTimeField()
        activity = models.TextField(max_length = 300)
        place = models.TextField(max_length = 300, null=True)
        category = models.TextField	(max_length = 300, null=True)

lab_2/models.py
from django.db import models

# Create your models here.

lab_8/models.py
from django.db import models

# Create your models here.

lab_1/views.py
from django.shortcuts import render, redirect
from datetime import datetime, date
from .models import Schedule
# Enter your name here
mhs_name = 'Adhiba Mastura' # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(1998, 12, 9) #TODO Implement this, format (Year, Month, Date)
npm = 1706074764 # TODO Implement this
# Create your views here.
def index(request):
    response = {'name': mhs_name, 'age': calculate_age(birth_date.year), 'npm': npm}
    return render(request, 'index_lab1.html', response)

def home(request):
    response = {}
    return render(request, 'home.html', response)

def about(request):
    response = {}
    return render(request, 'about.html', response)

def critics(request):
    response = {}
    return render(request, 'critics.html', response)

def form(request):
    response = {}
    return render(request, 'form.html', response)

def schedule(request):
    response = {}
    if request.method=='POST' and 'add' in request.POST:
        date = datetime.strptime(request.POST['date'],'%Y-%m-%dT%H:%M')
        activity = request.POST['activity']
        place = request.POST['place']
        category = request.POST['category']
        Schedule.objects.create(date = date, activity = activity, place = place, category = category)
        return redirect('/lab-1/schedule')

    if request.method=='POST' and 'deleteall' in request.POST:
        Schedule.objects.all().delete()
        return redirect('/lab-1/schedule')

    response['schedule_dict'] = Schedule.objects.all().values()

    return render(request, 'schedule.html', response)

def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0

lab_2/views.py
from django.shortcuts import render
from lab_1.views import mhs_name, birth_date

#TODO Implement
#Create a content paragraph for your landing page:
landing_page_content = ''

def index(request):
    response = {'name': mhs_name, 'content': landing_page_content}
    return render(request, 'index_lab2.html', response)

lab_8/views.py
from django.shortcuts import render, redirect

def index(request):
    response = {}
    return render(request, 'index.html', response)

lab_1/templates/index_lab1.html
<!DOCTYPE html>
<html>
<head>
<title> LAB 1 - PPW </title>
<style>
body {
  background-image: url("https://preview.ibb.co/cyK9Ee/sandy.jpg");
  height: 500px;
  background-position: top right;
  background-size: cover;
  position: relative;
}
h1   {color: black;
	  text-align: center;
	  font-family: verdana;}
h2    {color: white;
	  text-align: center;
	  font-family: verdana;}
p    {color: white;
	  font-family: verdana;}
</style>
</head>
<body>

<h1>ADHIBA MASTURA</h1>
<center> <a href="https://ibb.co/epGZfK"><img src="https://preview.ibb.co/kbVufK/dhb.jpg" alt="dhb" border="0" style="width:250px; height:250px"></a> </center>
<br> <br>
<p> <strong> My name </strong> is Adhiba Mastura </p>
<p> <strong> My NPM </strong> is 1706074764 </p>
<p> <strong> Im currently studying </strong> Information System at Faculty of Computer Science, University of Indonesia. </p>
<br>
<h2> ABOUT ME </h2>
<p> Hi! my name is Dhiba and I am 19 years old. I live in Depok with my parents, two brothers and one sister. I love to cook and watch thriller or action movies. I also like to read novels and listen to music. </p>
<br> <br> <br>
<h2> MY FRIENDS </h2>
<center> <a href="https://ibb.co/itDrSz"><img src="https://preview.ibb.co/d8iEfK/aurel.jpg" alt="aurel" border="0" style="width:250px; height:250px"></a> </center>
<p> <strong> Name: </strong> Aurellia Dhya Andini </p>
<p> <strong> NPM: </strong> 1706022022 </p>
<p> <strong> Hobby: </strong> listening to music </p>
<p> <strong> Short Description: </strong> I live in Depok with my parents and my sister. I like to watch TV shows and romantic comedy movies. </p>
<br> <br>
<center> <a href="https://ibb.co/gG3GSz"><img src="https://preview.ibb.co/cdHbSz/lula.jpg" alt="lula" border="0" style="width:250px; height:250px"></a> </center>
<p> <strong> Name: </strong> Thalia Talula Kesuma Putri </p>
<p> <strong> NPM: </strong> 1706984751 </p>
<p> <strong> Hobby: </strong> hangout with friends </p>
<p> <strong> Short Description: </strong> I live in Depok with my parents and my sister. I am 19 years old. </p>
</body>
</html>

lab_2/templates/description_lab2addon.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<body style="background-color: aqua">
    <h3 style="text-align: center">Hi all, This is my complete biodata</h3>
    <table align="center" style="text-align: center">
        {% for bio in bio_dict %}
            <tr>
                <td class="subject">{{ bio.subject }}</td>
                <td class="value">{{ bio.value }}</td>
            </tr>
        {% endfor %}
    </table>
    <br><br>
</body>

</html>

lab_2/templates/index_lab2.html
{% extends "base.html" %}
{% block content %}
<style>
    .center_screen {
        position: absolute;
        width: 500px;
        height: 50px;
        top: 50%;
        left: 50%;
        margin-left: -250px; /* margin is -0.5 * dimension */
        margin-top: -25px;
    }
</style>
<div class="center_screen">
    <p class="status" id="test">Hello, this is {{ name }}. {{ content }}.</p>
</div>
{% endblock %}

lab_8/templates/index.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title> Adhiba Mastura </title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/tema1.css' %}" class="theme-style">
<script src="{% static 'js/script.js' %}"></script>
<script src="{% static 'js/jquery-3.3.1.js' %}"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <div class='progress' id="progress_div">
        <div class='bar' id='bar1'></div>
        <div class='percent' id='percent1'></div>
    </div>
    <!-- Card -->
    <div class="card card-image">
      <h1> Selamat Datang! </h1>

        <!-- Content -->
        <div class="rgba-black-strong py-5 px-4">
            <div class="row d-flex justify-content-center">
                <div class="col-md-10 col-xl-8">

                    <!--Accordion wrapper-->
                    <div class="accordion md-accordion accordion-5" id="accordionEx5" role="tablist" aria-multiselectable="true">

                        <!-- Accordion card -->
                        <div class="card mb-4">

                            <!-- Card header -->
                            <div class="card-header p-0 z-depth-1" role="tab" id="heading30" name="heading30">
                                <a data-toggle="collapse" data-parent="#accordionEx5" href="#collapse30" aria-expanded="true" aria-controls="collapse30">
                                    <i class="fa fa-cloud fa-2x p-3 mr-4 float-left black-text" aria-hidden="true"></i>
                                    <h4 class="text-uppercase white-text mb-0 py-3 mt-1">
                                        Profil
                                    </h4>
                                </a>
                            </div>

                            <!-- Card body -->
                            <div id="collapse30" class="collapse show" role="tabpanel" aria-labelledby="heading30" data-parent="#accordionEx5">
                                <div class="card-body rgba-black-light white-text z-depth-1">
                                  <center><img src="https://preview.ibb.co/kbVufK/dhb.jpg" border="0" style="width: 20%; height: 20%;"></center>
                                    <p class="p-md-4 mb-0">Halo! Nama saya Adhiba Mastura, biasa dipanggil Dhiba. Umur saya 19 tahun dan saya tinggal di Cinere. Saya memiliki dua kakak dan satu adik. Hobi saya adalah menonton film. Saya sedang menjalani pendidikan di Univeritas Indonesia, Fakultas Ilmu Komputer dan jurusan Sistem Informasi. Website ini adalah salahsatu tugas saya dari mata kuliah Perancangan dan Pemrograman Web. Sekarang, saya sedang mengikuti 2 kepanitiaan, yaitu menjadi Bendahara di CGT 2019 dan menjadi Wakil Penanggungjawab Stage di Compfest 11.</p>
                                </div>
                            </div>
                        </div>
                        <!-- Accordion card -->

                        <!-- Accordion card -->
                        <div class="card mb-4">

                            <!-- Card header -->
                            <div class="card-header p-0 z-depth-1" role="tab" id="heading31">
                                <a data-toggle="collapse" data-parent="#accordionEx5" href="#collapse31" aria-expanded="true" aria-controls="collapse31">
                                    <i class="fa fa-commenting-o fa-2x p-3 mr-4 float-left black-text" aria-hidden="true"></i>
                                    <h4 class="text-uppercase white-text mb-0 py-3 mt-1">
                                        Pengalaman Kepanitiaan
                                    </h4>
                                </a>
                            </div>

                            <!-- Card body -->
                            <div id="collapse31" class="collapse" role="tabpanel" aria-labelledby="heading31" data-parent="#accordionEx5">
                                <div class="card-body rgba-black-light white-text z-depth-1">
                                    <p class="p-md-4 mb-0">Sebelum saya kuliah di Fasilkom, saya mengikuti beberapa kepanitiaan seperti mengurus acara tahunan di SMA saya dan musik festival bernama Archipelago Festival. Setelah masuk Fasilkom, saya mengikuti beberapa kepanitiaan. Saya pernah menjadi Staff Stage di Compfest X, Bendahara di Wisuda Genap 2018 dan LO di OH Fasilkom 2018.</p>
                                </div>
                            </div>
                        </div>
                        <!-- Accordion card -->

                        <!-- Accordion card -->
                        <div class="card mb-4">

                            <!-- Card header -->
                            <div class="card-header p-0 z-depth-1" role="tab" id="heading32">
                                <a data-toggle="collapse" data-parent="#accordionEx5" href="#collapse32" aria-expanded="true" aria-controls="collapse32">
                                    <i class="fa fa-cogs fa-2x p-3 mr-4 float-left black-text" aria-hidden="true"></i>
                                    <h4 class="text-uppercase white-text mb-0 py-3 mt-1">
                                        Prestasi
                                    </h4>
                                </a>
                            </div>

                            <!-- Card body -->
                            <div id="collapse32" class="collapse" role="tabpanel" aria-labelledby="heading32" data-parent="#accordionEx5">
                                <div class="card-body rgba-black-light white-text z-depth-1">
                                    <p class="p-md-4 mb-0">Alhamdulillah, selama di Fasilkom saya belum ada prestasi, mohon doanya agar saya bisa menambah prestasi saya. :)</p>
                                </div>
                            </div>
                        </div>
                        <!-- Accordion card -->
                    </div>
                    <!--/.Accordion wrapper-->

                </div>
            </div>
        </div>
        <!-- Content -->
        <div class="row">
        <div class="col-12">
          <center><button class="button theme-color" id="tema" onclick="changeTheme();"> Ubah Tema </button></center>
        </div>
      </div>
    </div>
    <!-- Card -->
    <input type="hidden" id="progress_width" value="0">
</body>
</html>

templates/about.html
{% include 'navbar.html' %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title> Adhiba Mastura - About</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style type="text/css">
body {
	background-image: url("https://preview.ibb.co/hvP3mp/aboutbg.jpg");
	background-repeat: repeat;
	background-size: contain;
}
</style>
</head>
<body>
	<br/>
	<div class="row">
		<div class="col-3"> </div>
		<div class="col-3">
			<h3> LETS GET PERSONAL! </h3>
			<p>Hi! My name is Adhiba Mastura and I'm 19 years old. I live with my two brothers, my sister and my parents in Depok. I love to cook and watch thriller or action movies. I'm currently studying Information System at Faculty of Computer Science, University of Indonesia.</p>
		</div>
		<img src="https://preview.ibb.co/kbVufK/dhb.jpg" border="0" style="width: 20%; height: 20%;">
	</div>
	<center> <h3 id="my-fam"> MY FAMILY </h3>
		<img src="https://preview.ibb.co/kjFZge/hakam.jpg" alt="hakam" border="0" style="width: 11%; height: 11%;">
		<img src="https://preview.ibb.co/hX9AMe/abg.jpg" alt="abg" border="0" style="width: 11%; height: 11%;">
		<img src="https://preview.ibb.co/j6SVMe/kak.jpg" alt="kak" border="0" style="width: 11%; height: 11%;">
		<img src="https://preview.ibb.co/gqcrSK/bunda.jpg" alt="bunda" border="0" style="width: 11%; height: 11%;">
		<img src="https://preview.ibb.co/kg1eEz/ayah.jpg" alt="ayah" border="0" style="width: 11%; height: 11%;">
		<br>
		<br>
	</center>
	<center> <h3 id="my-frds"> MY FRIENDS </h3>
		<img src="https://preview.ibb.co/mLsfMe/azh.jpg" alt="azh" border="0" style="width: 12%; height: 12%;">
		<img src="https://preview.ibb.co/jzWqMe/h7.jpg" alt="h7" border="0" style="width: 12%; height: 12%;">
		<br/> <br/> <br/>
	</center>

</body>
</html>
{% include 'footer.html' %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<body style="background-color: lightgray">
    <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/lab-2/">Home</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="/lab-2-addon/">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/lab-3/">Diary</a>
              </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}
</html>

templates/critics.html
{% include 'navbar.html' %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title> Adhiba Mastura - Feedback</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style type="text/css">
body {
	background-image: url("https://preview.ibb.co/hvP3mp/aboutbg.jpg");
	background-repeat: repeat;
	background-size: contain;
}
</style>
</head>
<body>
	<form action="">
		<div class="col-8">
			<br>
			Tell me what you think about my website! :<br> <br>
	  		<input type="text" name="Critics" style="height: 200px; padding: 12px 12px 12px 0;">
	  		<br><br>
	  		<button class="button-button-1"> Submit </button>
	  		<br> <br> <br> <br> <br>
	  	</div>
	</form>
</body>
</html>
{% include 'footer.html' %}

templates/description_lab2addon.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hi all, This is my complete biodata</h3>
<table align="center" style="text-align: center">
    {% for bio in bio_dict %}
        <tr>
            <td class="subject">{{ bio.subject }}</td>
            <td class="value">{{ bio.value }}</td>
        </tr>
    {% endfor %}
</table>
<br><br>
{% endblock %}

templates/footer.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<footer>

	<div class = "footer">
		<br>
		<div class="container-fluid">
			<div class="row-10">
				<center>
				<div class="column">
					<img class='img' src="https://image.flaticon.com/icons/svg/482/482948.svg" border="0" style="width: 4%; height: 4%">
					<img class='img' src="https://image.flaticon.com/icons/svg/1051/1051333.svg" border="0" style="width: 4%; height: 4%">
					<img class='img' src="https://image.flaticon.com/icons/svg/15/15886.svg" border="0" style="width: 4%; height: 4%">
					<img class='img' src="https://image.flaticon.com/icons/svg/87/87390.svg" border="0" style="width: 4%; height: 4%">
				</div>
				</center>
			</div>
		</div>
		<br>
	</div>

</footer>
</html>

templates/form.html
{% include 'navbar.html' %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title> Adhiba Mastura - Register</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style type="text/css">
body {
	background-image: url("https://preview.ibb.co/hvP3mp/aboutbg.jpg");
	background-repeat: repeat;
	background-size: contain;
}
</style>
</head>
<body>
	<form action="">
		<div class="col-8">
			<br>
			Name :<br>
	  		<input type="text" name="Name">
	  		<br> <br>
	  		Date of Birth :<br>
	  		<input type="date" name="DoB">
	  		<br> <br>
	  		Email :<br>
	  		<input type="Email" name="Email">
	  		<br> <br>
	  		Username :<br>
	  		<input type="text" name="Username">
	  		<br> <br>
	  		Password :<br>
	  		<input type="Password" name="Passowrd">
	  		<br> <br>
	  		Password Confirmation :<br>
	  		<input type="Password" name="PasswordConfirmation">
	  		<br><br>
	  		<button class="button-button-2"> Register </button>
	  		<br> <br>
	  	</div>
	</form>
</body>
</html>
{% include 'footer.html' %}

templates/home.html
{% include 'navbar.html' %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title> Adhiba Mastura - Home</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style type="text/css">
body {
	background-image: url("https://preview.ibb.co/nf7Omp/homebg.jpg");
	background-repeat: repeat;
	background-size: contain;
}
</style>
</head>
<body>
	<div class="container-fluid">
		<div class="row">
			<div class="col">
				<h1> WELCOME! I'M DHIBA. </h1>
				<h3> I'D RATHER BE COOKING BUT HERE WE ARE, SO ENJOY! :) </h3>
				<br> <br> <br> <br> <br> <br> <br>
			</div>
		</div>
	</div>
</body>
</html>
{% include 'footer.html' %}

templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<div class="container-fluid">
		<div class="row">
			<div class="col">
				<nav class="navbar navbar-expand-sm justify-content-center" id="my-navbar">
				  <ul class="navbar-nav">
				    <li class="nav-item">
				      <a href="{% url 'lab_1:home' %}" class="nav-link"> HOME </a>
				    </li>
				    <li class="nav-item">
				      <a href="{% url 'lab_1:about' %}" class="nav-link"> ABOUT </a>
				    </li>
				    <li class="nav-item">
				      <a href="{% url 'lab_1:critics' %}" class="nav-link"> FEEDBACK </a>
				    </li>
				    <li class="nav-item">
				      <a href="{% url 'lab_1:form' %}" class="nav-link"> REGISTER </a>
				    </li>
				    <li class="nav-item">
				      <a href="{% url 'lab_1:schedule' %}" class="nav-link"> SCHEDULE </a>
				    </li>
				  </ul>
				</nav>
			</div>
		</div>
	</div>
</body>
</html>